import type { SectionStatus, SectionType, TableRow } from './types'

type Tuple = [string, SectionType, SectionStatus, number, number, string]

// Mirrors the shadcn "dashboard-01" proposal-sections dataset: 68 rows / 7 pages.
const rows: Tuple[] = [
  ['Cover page', 'Cover page', 'In Process', 18, 5, 'Eddie Lake'],
  ['Table of contents', 'Table of contents', 'Done', 29, 24, 'Eddie Lake'],
  ['Executive summary', 'Narrative', 'Done', 10, 13, 'Eddie Lake'],
  ['Technical approach', 'Narrative', 'Done', 27, 23, 'Jamik Tashpulatov'],
  ['Design', 'Narrative', 'In Process', 2, 16, 'Jamik Tashpulatov'],
  ['Capabilities', 'Narrative', 'In Process', 20, 8, 'Jamik Tashpulatov'],
  ['Integration with existing systems', 'Narrative', 'In Process', 19, 21, 'Jamik Tashpulatov'],
  ['Innovation and Advantages', 'Narrative', 'Done', 25, 26, ''],
  ["Overview of EMR's Innovative Solutions", 'Technical content', 'Done', 7, 23, ''],
  ['Advanced Algorithms and Machine Learning', 'Narrative', 'Done', 30, 28, ''],
  ['Adaptive Communication Protocols', 'Narrative', 'Done', 9, 31, ''],
  ['Advantages Over Current Technologies', 'Narrative', 'Done', 12, 17, ''],
  ['Past Performance', 'Narrative', 'Done', 22, 19, 'Eddie Lake'],
  ['Customer Feedback and Satisfaction Levels', 'Narrative', 'Done', 15, 14, 'Eddie Lake'],
  ['Implementation Challenges and Solutions', 'Narrative', 'Done', 3, 9, 'Jamik Tashpulatov'],
  [
    'Security Measures and Data Protection Policies',
    'Narrative',
    'In Process',
    24,
    12,
    'Jamik Tashpulatov',
  ],
  ['Scalability and Future Proofing', 'Narrative', 'Done', 11, 27, 'Jamik Tashpulatov'],
  ['Cost-Benefit Analysis', 'Financial', 'In Process', 5, 20, 'Emily Whalen'],
  ['User Training and Onboarding Experience', 'Narrative', 'Done', 8, 25, 'Emily Whalen'],
  ['Future Development Roadmap', 'Narrative', 'In Process', 16, 6, 'Emily Whalen'],
  ['System Architecture Overview', 'Technical content', 'In Process', 22, 15, 'Jamik Tashpulatov'],
  ['Risk Management Plan', 'Narrative', 'Done', 14, 18, 'Emily Whalen'],
  ['Compliance Documentation', 'Legal', 'In Process', 30, 21, 'Jamik Tashpulatov'],
  ['API Documentation', 'Technical content', 'Done', 12, 10, 'Eddie Lake'],
  ['Data Migration Strategy', 'Technical content', 'Done', 17, 22, 'Jamik Tashpulatov'],
  ['Quality Assurance Protocols', 'Narrative', 'In Process', 6, 11, 'Emily Whalen'],
  ['Deployment Timeline', 'Narrative', 'Done', 21, 16, 'Eddie Lake'],
  ['Maintenance and Support Plan', 'Narrative', 'In Process', 4, 29, 'Jamik Tashpulatov'],
  ['Disaster Recovery Procedures', 'Technical content', 'Done', 26, 7, 'Emily Whalen'],
  ['Third-Party Integrations', 'Technical content', 'In Process', 13, 30, ''],
  ['User Interface Design Principles', 'Narrative', 'Done', 28, 12, 'Eddie Lake'],
  ['Accessibility Compliance', 'Legal', 'Done', 19, 24, 'Emily Whalen'],
  ['Performance Benchmarks', 'Technical content', 'In Process', 23, 13, 'Jamik Tashpulatov'],
  ['Vendor Management Approach', 'Narrative', 'Not Started', 7, 26, ''],
  ['Stakeholder Communication Plan', 'Narrative', 'Done', 15, 20, 'Eddie Lake'],
  ['Change Management Process', 'Narrative', 'In Process', 9, 17, 'Emily Whalen'],
  ['Budget Breakdown', 'Financial', 'Done', 31, 8, 'Emily Whalen'],
  ['Resource Allocation Model', 'Financial', 'In Process', 18, 23, 'Jamik Tashpulatov'],
  ['Return on Investment Projections', 'Financial', 'Done', 11, 5, 'Emily Whalen'],
  ['Licensing and Intellectual Property', 'Legal', 'Not Started', 25, 14, ''],
  ['Service Level Agreements', 'Legal', 'Done', 20, 27, 'Eddie Lake'],
  ['Privacy Policy Alignment', 'Legal', 'In Process', 5, 19, 'Jamik Tashpulatov'],
  ['Core Platform Capabilities', 'Capabilities', 'Done', 27, 9, 'Eddie Lake'],
  ['Reporting and Analytics Suite', 'Capabilities', 'Done', 14, 22, 'Emily Whalen'],
  ['Workflow Automation Engine', 'Capabilities', 'In Process', 8, 31, 'Jamik Tashpulatov'],
  ['Mobile Access and Offline Mode', 'Capabilities', 'Not Started', 16, 10, ''],
  ['Interoperability Standards', 'Capabilities', 'Done', 29, 18, 'Eddie Lake'],
  ['Clinical Decision Support', 'Technical content', 'In Process', 3, 25, 'Jamik Tashpulatov'],
  ['Audit Logging and Traceability', 'Technical content', 'Done', 21, 6, 'Emily Whalen'],
  ['Identity and Access Management', 'Technical content', 'Done', 10, 28, 'Jamik Tashpulatov'],
  ['Encryption at Rest and in Transit', 'Technical content', 'In Process', 24, 11, 'Eddie Lake'],
  ['Incident Response Playbook', 'Focus Documents', 'Done', 6, 16, 'Emily Whalen'],
  ['Business Continuity Assessment', 'Focus Documents', 'In Process', 30, 20, 'Jamik Tashpulatov'],
  ['Environmental Impact Statement', 'Focus Documents', 'Not Started', 12, 7, ''],
  ['Diversity and Inclusion Commitments', 'Focus Documents', 'Done', 22, 29, 'Eddie Lake'],
  ['Subcontractor Qualifications', 'Focus Documents', 'In Process', 17, 13, 'Emily Whalen'],
  ['Key Personnel Biographies', 'Focus Documents', 'Done', 4, 24, 'Eddie Lake'],
  ['Organizational Chart', 'Focus Documents', 'Done', 26, 15, 'Jamik Tashpulatov'],
  ['Case Study: Regional Health Network', 'Narrative', 'Done', 13, 21, 'Emily Whalen'],
  ['Case Study: Multi-Site Rollout', 'Narrative', 'In Process', 28, 8, 'Jamik Tashpulatov'],
  ['Reference Letters', 'Focus Documents', 'Not Started', 9, 30, ''],
  ['Pricing Schedule', 'Financial', 'Done', 19, 12, 'Emily Whalen'],
  ['Payment Milestones', 'Financial', 'In Process', 7, 26, 'Eddie Lake'],
  ['Warranty and Guarantees', 'Legal', 'Done', 23, 17, 'Jamik Tashpulatov'],
  ['Terms and Conditions', 'Legal', 'Done', 15, 5, 'Eddie Lake'],
  ['Glossary of Terms', 'Narrative', 'In Process', 2, 23, ''],
  [
    'Appendix A: Technical Specifications',
    'Technical content',
    'Done',
    31,
    19,
    'Jamik Tashpulatov',
  ],
  ['Appendix B: Supporting Data', 'Technical content', 'Not Started', 20, 9, ''],
]

export const tableData: TableRow[] = rows.map(
  ([header, type, status, target, limit, reviewer], i) => ({
    id: i + 1,
    header,
    type,
    status,
    target,
    limit,
    reviewer,
  }),
)
